export const LANGUAGE_ARRAY = [
    {label: 'Assembly', value: 'assembly',ide:{name: "gas", architecture: "ARM"}},
    {label: 'ATS', value: 'ats',ide:'text/x-gas'},
    {label: 'Bash', value: 'bash',ide:''},
    {label: 'C', value: 'c',ide:'text/x-csrc'},
    {label: 'Clojure', value: 'clojure',ide:'text/x-clojure'},
    {label: 'COBOL', value: 'cobol',ide:'cobol'},
    {label: 'Coffeescript', value: 'coffeescript',ide:'text/x-coffeescript'},
    {label: 'C++', value: 'cpp', ide:'text/x-c++src'},
    {label: 'Crystal', value: 'crystal',ide:'text/x-crystal'},
    {label: 'C#', value: 'csharp',ide:'text/x-csharp'},
    {label: 'D', value: 'd',ide:'text/x-d'},
    {label: 'Elixir', value: 'elixir',ide:'elixir'},
    {label: 'Elm', value: 'elm',ide:'text/x-elm'},
    {label: 'Erlang', value: 'erlang',ide:'text/x-erlang'},
    {label: 'F#', value: 'fsharp',ide:'text/x-fsharp'},
    {label: 'Go', value: 'go',ide:'text/x-go'},
    {label: 'Groovy', value: 'groovy',ide:'text/x-groovy'},
    {label: 'Haskell', value: 'haskell',ide:'text/x-haskell'},
    {label: 'Idris', value: 'idris',ide:''},
    {label: 'Java', value: 'java',ide:'text/x-java'},
    {label: 'JavaScript', value: 'javascript',ide:'text/javascript'},
    {label: 'Julia', value: 'julia',ide:'text/x-julia'},
    {label: 'Kotlin', value: 'kotlin',ide:'clike'},
    {label: 'Lua', value: 'lua',ide:'text/x-lua'},
    {label: 'Mercury', value: 'mercury',ide:''},
    {label: 'Nim', value: 'nim',ide:''},
    {label: 'Ocaml', value: 'ocaml',ide:'text/x-ocaml'},
    {label: 'Perl', value: 'perl',ide:'text/x-perl'},
    {label: 'PHP', value: 'php',ide:'text/x-php'},
    {label: 'Python', value: 'python',ide:'text/x-python'},
    {label: 'Raku', value: 'raku',ide:''},
    {label: 'Ruby', value: 'ruby',ide:'text/x-ruby'},
    {label: 'Rust', value: 'rust',ide:'text/x-rustsrc'},
    {label: 'Scala', value: 'scala',ide:'text/x-scala'},
    {label: 'Swift', value: 'swift',ide:'text/x-swift'},
    {label: 'Typescript', value: 'typescript',ide:'text/typescript'}
];
