export const LANGUAGE_ARRAY = [
    {label: 'Assembly', value: 'assembly',ide:''},
    {label: 'ATS', value: 'ats',ide:''},
    {label: 'Bash', value: 'bash',ide:''},
    {label: 'C', value: 'c',ide:'clike'},
    {label: 'Clojure', value: 'clojure',ide:'clike'},
    {label: 'COBOL', value: 'cobol',ide:'cobol'},
    {label: 'Coffeescript', value: 'coffeescript',ide:'coffeescript'},
    {label: 'C++', value: 'cpp', ide:'clike'},
    {label: 'Crystal', value: 'crystal',ide:'crystal'},
    {label: 'C#', value: 'csharp',ide:'clike'},
    {label: 'D', value: 'd',ide:'d'},
    {label: 'Elixir', value: 'elixir',ide:'elixir'},
    {label: 'Elm', value: 'elm',ide:'elm'},
    {label: 'Erlang', value: 'erlang',ide:'erlang'},
    {label: 'F#', value: 'fsharp',ide:'mllike'},
    {label: 'Go', value: 'go',ide:'go'},
    {label: 'Groovy', value: 'groovy',ide:'groovy'},
    {label: 'Haskell', value: 'haskell',ide:'haskell'},
    {label: 'Idris', value: 'idris',ide:''},
    {label: 'Java', value: 'java',ide:'clike'},
    {label: 'JavaScript', value: 'javascript',ide:'javascript'},
    {label: 'Julia', value: 'julia',ide:'julia'},
    {label: 'Kotlin', value: 'kotlin',ide:'clike'},
    {label: 'Lua', value: 'lua',ide:'lua'},
    {label: 'Mercury', value: 'mercury',ide:''},
    {label: 'Nim', value: 'nim',ide:''},
    {label: 'Ocaml', value: 'ocaml',ide:'mllike'},
    {label: 'Perl', value: 'perl',ide:'perl'},
    {label: 'PHP', value: 'php',ide:'php'},
    {label: 'Python', value: 'python',ide:'python'},
    {label: 'Raku', value: 'raku',ide:''},
    {label: 'Ruby', value: 'ruby',ide:'ruby'},
    {label: 'Rust', value: 'rust',ide:'rust'},
    {label: 'Scala', value: 'scala',ide:'clike'},
    {label: 'Swift', value: 'swift',ide:'swift'},
    {label: 'Typescript', value: 'typescript',ide:'javascript'}
];
