version: "3.7"

networks:
  myapp:
    driver: bridge

services:
  codeeditor:
    container_name: codeEditor
    restart: always
    build: .
    ports:
      - "443:443"
      - "80:8080"
    links:
      - mongobase
    networks:
      - myapp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/letsencrypt/live/codetalk.pro/privkey.pem:/etc/letsencrypt/live/codetalk.pro/privkey.pem
      - /etc/letsencrypt/live/codetalk.pro/cert.pem:/etc/letsencrypt/live/codetalk.pro/cert.pem
    env_file:
      - env.list
    environment:
      - MONGO_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
  peerjsserver:
    restart: always
    container_name: peerjsserver
    build: ./peerjsserver/
    volumes:
      - /etc/letsencrypt/live/codetalk.pro/privkey.pem:/etc/letsencrypt/live/codetalk.pro/privkey.pem
      - /etc/letsencrypt/live/codetalk.pro/cert.pem:/etc/letsencrypt/live/codetalk.pro/cert.pem
    ports:
    - '9000:9000'
  mongobase:
    container_name: mongobase
    hostname: mongobase
    image: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
    ports:
      - "27018:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - dbdatamongo:/data/db
    networks:
      - myapp

volumes:
  dbdatamongo:
